name: Publish Docker

on:
  push:
    tags:
      - 'indexer-*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.x'
  
      - name: Install dependencies
        run: go mod download

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: script3
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#indexer-}" >> $GITHUB_OUTPUT

      - name: Build and push indexer
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.indexer
          platforms: linux/amd64
          push: true
          tags: script3/governor-indexer:latest,script3/governor-indexer:${{ steps.version.outputs.VERSION }}
